### PR TITLE
Two fixes and one feature

### PR DESCRIPTION
**Pull request by marcorieser**
- Added .hidden-xlg class (Fix for #51 )
- Put properties with star hack inside a legacy condition

### CODE REVIEW

**Comment by leejordan** [comment]
Thanks. Looks good. I'm a bit short of time at the moment but I'll sort this in the near future. :+1:

**Comment by marcorieser** [comment]
Fix for request #49

**Comment by marcorieser** [comment]
Sorry for not making a feature branch for each fix.

**Comment by leejordan** [comment]
Hey man no problem at all I'm just really grateful for your assistance. I'll take a look over it all when I get a chance.

Thanks again.

**Review by leejordan — APPROVED** [review]
These all look perfect to me. Just gonna add some bits to the docs to cover the additions and in so doing, give everything a test.

Thanks

**Comment by marcorieser** [comment]
👍🏻

**Pull request merged**
