### PR TITLE
Version2

### PR DESCRIPTION
**Pull request by leejordan**
Version 2 of reflex grid which is not compatible with version 1. Many things have changed in version 2 which will need addressing if you want to update.

- All class names have dropped the `grid__` and `grid--` prefixes but are otherwise unchanged
- Columns are no longer flexbox by default. They can be converted to flexbox containers with the `col-grid` class
- There is far better support for older browsers, particularly the ie10 implementation of flexbox
- Added container classes
- Added better support for "cards" as well as some example code
- Is now only built with SCSS. Older versions had both LESS and SCSS implementations but this was too much to support and I have now personally moved to SCSS as my CSS building tool of choice so it didn't make sense to support them both any more.

### CODE REVIEW

**Comment by frabonomi** [comment]
Hey @leejordan so you're basically dropping the BEM syntax. That's one of the features that made me choose this grid. Any reason for changing that?

**Comment by leejordan** [comment]
hey @frabonomi yea basically I was writing a blog post about this but I haven't managed to publish it yet... I wasn't really being faithful to BEM by having modifiers applied to both grid and col elements. This inconsistency bothered me. In addition to that I was also coming around to the idea of BEM only being really applicable to self-contained modules rather than something that can work with a framework like this. I'm happy to be convinced otherwise and may consider changing it back but ultimately I use this grid for my own work and version 2 is the the result of many months of constantly overriding the defaults I originally set in place. Version 2 is really the culmination of my personal use for this framework.

With hindsight, I can see that maybe with my new approach (with cols not being flex elements by default) it's possibly *more* compatible with BEM than it was before. Happy to discuss it further and will consider changing it back if it's something that makes sense. Feel free to add your input below and thanks for your input so far. I appreciate it. Don't forget this is really a personal project of mine and sometimes I forget that so many other people use it.

**Comment by leejordan** [comment]
One more thing - BEM use aside, this version 2 is really much more stable and reliable than earlier versions. I have finally deciphered fully the horrible ie10 flexbox implementation and it now fully works in those browsers rather than just half working as it did before.

**Comment by frabonomi** [comment]
Thanks for you reply @leejordan! Yeah, I did notice the inconsistencies and I also thought about BEM not being a great idea for a thing such as a grid. Its verbosity is sometimes annoying, but at the same time I like the fact that it's descriptive. And above all I liked the fact I finally found a grid that was using flexbox and followed naming conventions that matched the rest of our codebase.

I still didn't check out version 2, I'll definitely do that when I have some time. And I'll be happy to have a look and see if maybe reintroducing BEM makes any sense or not. I even wonder if it could be an optional thing maybe. Though I have to admit that when I picked this grid the fact that was using BEM was definitely an important plus :)

Btw thanks for the responsiveness in replying, really appreciate your work. Let me know when you publish the article, interested to read about it!

**Comment by leejordan** [comment]
I forgot to publish this but here's the blog post. Any suggestions please let me know. I'd be especially interested in a rough outline of how a BEM structure would work in spite of the inconsistencies I outlined in this blog post

http://lendmeyourear.net/reflex-grid-version-2.html

**Pull request merged**
